In [1]:
#part1
import pandas as pd

df = pd.read_csv("HousePricePrediction.csv")

In [2]:
df.shape
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2918.000000,1460.000000
mean,1459.000000,57.137718,10168.114080,5.564577,1971.312778,1984.264474,49.582248,1051.777587,180921.195890
std,842.787043,42.517628,7886.996359,1.113131,30.291442,20.894344,169.205611,440.766258,79442.502883
min,0.000000,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,729.500000,20.000000,7478.000000,5.000000,1953.500000,1965.000000,0.000000,793.000000,129975.000000
50%,1459.000000,50.000000,9453.000000,5.000000,1973.000000,1993.000000,0.000000,989.500000,163000.000000
75%,2188.500000,70.000000,11570.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,214000.000000
max,2918.000000,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

In [ ]:
#data preprocessing-data cleaning
df.drop9['Id'],
            axis=1
            inplace=True)
#replacing SalePrice empty values with their mean values
df['SalePrice'].mean())
#drop records with null values
df=df.dropna()
df.isnull().sum()
df.head()

In [ ]:
#data-preprocessing-encoding
cols=['MSZoing','LotConfig','BldgType','Exterior1st']
df=pd.get_dummies(df,columns=cols,drop_first=True)

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
X=df.drop(['SalePrice'],axis= 1)
Y=df['SalePrice']
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=0)

In [ ]:
X_train.head()

In [2]:
#part3
import pandas as pd

df = pd.read_csv("iris.csv")

In [6]:
df.head()
df.info
df.shape
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [7]:
#convert 3 species into 0,1,2
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Species']= le.fit_transform(df['Species'])
df.sample(10)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
82    83            5.8           2.7            3.9           1.2        1
21    22            5.1           3.7            1.5           0.4        0
8      9            4.4           2.9            1.4           0.2        0
73    74            6.1           2.8            4.7           1.2        1
37    38            4.9           3.1            1.5           0.1        0
90    91            5.5           2.6            4.4           1.2        1
69    70            5.6           2.5            3.9           1.1        1
60    61            5.0           2.0            3.5           1.0        1
124  125            6.7           3.3            5.7           2.1        2
36    37            5.5           3.5            1.3           0.2        0

In [9]:
from sklearn.model_selection import train_test_split
X=df.drop('Species',axis=1)
y=df['Species']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state=42)

In [11]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [12]:
#KNN 
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [13]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [20]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
models={'Logistic Regression': lr,'KNN':knn,'Naive Bayes': nb}
for name,model in models.items():
    y_pred=model.predict(X)
    print(f"\n{name}")
    print("Accuracy :",accuracy_score(y,y_pred))
    
    print("cm :",confusion_matrix(y,y_pred))
    
    print("Classification report :",classification_report(y,y_pred))

Logistic Regression
Accuracy : 1.0
cm : [[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]
Classification report :               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        50
           2       1.00      1.00      1.00        50

    accuracy                           1.00       150
   macro avg       1.00      1.00      1.00       150
weighted avg       1.00      1.00      1.00       150


KNN
Accuracy : 0.9933333333333333
cm : [[50  0  0]
 [ 0 49  1]
 [ 0  0 50]]
Classification report :               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      0.98      0.99        50
           2       0.98      1.00      0.99        50

    accuracy                           0.99       150
   macro avg       0.99      0.99      0.99       150
weighted avg       0.99      0.99      0.99       150


Naive Bayes
Accuracy : 0.9933333333333333
cm : [[50  0  0]
 [ 0 50  0]
 [ 0  1 49]]
Classification report :               precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.98      1.00      0.99        50
           2       1.00      0.98      0.99        50

    accuracy                           0.99       150
   macro avg       0.99      0.99      0.99       150
weighted avg       0.99      0.99      0.99       150

In [3]:
#part2
import pandas as pd
df=pd.read_csv("employee_turnover.csv")

In [4]:
df.info()
df.shape
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 16 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Job_Satisfaction                         1350 non-null   float64
 1   Performance_Rating                       1350 non-null   float64
 2   Years_At_Company                         1350 non-null   float64
 3   Work_Life_Balance                        1350 non-null   float64
 4   Distance_From_Home                       1350 non-null   float64
 5   Monthly_Income                           1350 non-null   float64
 6   Education_Level                          1350 non-null   float64
 7   Age                                      1350 non-null   float64
 8   Num_Companies_Worked                     1350 non-null   float64
 9   Employee_Role                            1350 non-null   float64
 10  Annual_Bonus                             1350 non-null   float64
 11  Training_Hours                           1350 non-null   float64
 12  Department                               1350 non-null   float64
 13  Annual_Bonus_Squared                     1350 non-null   float64
 14  Annual_Bonus_Training_Hours_Interaction  1350 non-null   float64
 15  Employee_Turnover                        1350 non-null   int64
dtypes: float64(15), int64(1)
memory usage: 168.9 KB

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
0,0.562326,0.141129,0.123989,0.347583,0.330353,0.328853,0.600933,0.315990,0.768736,0.090671,0.324786,0.669193,0.602932,0.105486,0.217344,0
1,0.017041,0.559047,0.511203,0.793908,0.423550,0.553450,0.742009,0.897146,0.380035,0.601633,0.694611,0.043271,0.800761,0.482484,0.030056,0
2,0.774699,0.604371,0.798174,0.260500,0.804034,0.131800,0.775178,0.830947,0.218726,0.972936,0.153476,0.701336,0.705275,0.023555,0.107638,1
3,0.628174,0.385249,0.230104,0.516809,0.272248,0.589249,0.482409,0.090507,0.402746,0.132842,0.305973,0.549688,0.600531,0.093620,0.168190,0
4,0.799183,0.199967,0.839029,0.247927,0.341934,0.076818,0.055356,0.680860,0.923341,0.493017,0.844094,0.793751,0.664679,0.712494,0.670000,0

In [5]:
X= df.drop('Employee_Turnover',axis=1)
y=df['Employee_Turnover']

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.2,random_state=42)

In [7]:
#Baseline logistic regression 
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression(max_iter=200)
lr.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [8]:
#L1_Regularization(lasso)
lasso=LogisticRegression(penalty='l1',solver='liblinear',C=0.5)
lasso.fit(X_train,y_train)

LogisticRegression(C=0.5, penalty='l1', solver='liblinear')

In [9]:
#L2_Regularization(ridge)
ridge=LogisticRegression(penalty='l2',C=1,max_iter=200)
ridge.fit(X_train,y_train)

LogisticRegression(C=1, max_iter=200)

In [10]:
#model_evaluation
from sklearn.metrics import accuracy_score, classification_report

models = {'Baseline': lr, 'Lasso': lasso, 'Ridge': ridge}

for name, model in models.items():
    y_pred = model.predict(X_test)
    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

Baseline
Accuracy: 0.8592592592592593
              precision    recall  f1-score   support

           0       0.85      0.90      0.87       145
           1       0.87      0.82      0.84       125

    accuracy                           0.86       270
   macro avg       0.86      0.86      0.86       270
weighted avg       0.86      0.86      0.86       270


Lasso
Accuracy: 0.8703703703703703
              precision    recall  f1-score   support

           0       0.86      0.90      0.88       145
           1       0.88      0.83      0.86       125

    accuracy                           0.87       270
   macro avg       0.87      0.87      0.87       270
weighted avg       0.87      0.87      0.87       270


Ridge
Accuracy: 0.8592592592592593
              precision    recall  f1-score   support

           0       0.85      0.90      0.87       145
           1       0.87      0.82      0.84       125

    accuracy                           0.86       270
   macro avg       0.86      0.86      0.86       270
weighted avg       0.86      0.86      0.86       270

In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score,classification_report,confusion_matrix

In [3]:
df=pd.read_csv("shop_smart_ecommerce.csv")
X=df.drop(columns=["Revenue"])
y=df["Revenue"].astype(int)#change the data type of a column or variable.

In [5]:
num_features=X.select_dtypes(include=["int64","float64"]).columns
cat_features=X.select_dtypes(include=["category","object"]).columns

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y#distribution of y equal on every sample 
)

In [11]:
#preprocessing Pipeline
preprocessor=ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),num_features),
        ("cat",OneHotEncoder(handle_unknown="ignore"),cat_features)

    ]
)

In [13]:
dt=DecisionTreeClassifier(
    max_depth=6,  #prevents deep overfitting
    min_samples_leaf=30,  #smooths decision boundaries
    class_weight="balanced"  , #handles imbalance
    random_state=42
)

In [19]:
pipe=Pipeline(
    steps=[
        ("preprocess",preprocessor),
        ("model",dt)
        
    ]
)

In [20]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['Month', 'VisitorType'], dtype='object'))])),
                ('model',
                 DecisionTreeClassifier(class_weight='balanced', max_depth=6,
                                        min_samples_leaf=30,
                                        random_state=42))])

In [21]:
y_pred=pipe.predict(X_test)

print("F1 score:",f1_score(y_test,y_pred))
print("\n Classification Report: \n",classification_report(y_test,y_pred))
print("\n F1 score:\n",confusion_matrix(y_test,y_pred))

F1 score: 0.6278381046396841

 Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.85      0.90      2084
           1       0.50      0.83      0.63       382

    accuracy                           0.85      2466
   macro avg       0.73      0.84      0.77      2466
weighted avg       0.89      0.85      0.86      2466


 F1 score:
 [[1771  313]
 [  64  318]]

In [23]:
from sklearn.model_selection import GridSearchCV

param_grid={
    "model__max_depth":[4,6,8],
    "model__min_samples_leaf":[20,30,50]

}
grid= GridSearchCV(
    pipe,
    param_grid,
    scoring="f1",
    cv=5,
    n_jobs=-1
)

grid.fit(X_train,y_train)

print("Best F1:",grid.best_score_)
print("Best params:",grid.best_params_)

Best F1: 0.6343735129725652
Best params: {'model__max_depth': 4, 'model__min_samples_leaf': 50}